sudo: required
services:
  - docker

before_install:
  - docker build -t gautvenk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gautvenk/docker-react npm run test -- --coverage

